# SeqTrainer Tutorial 00: Quickstart

This notebook introduces the core public API in a few minutes.

## Prerequisites

Install in editable mode from the repo root:

```bash
pip install -e .
```

Then run this notebook from the project root.

In [1]:
from seqtrainer import DatasetRecipe, MaterializedDataset
from seqtrainer.transforms.dna import normalize_sequence, gc_content

print("Imports loaded")

Imports loaded

## Create a tiny in-memory dataset

`MaterializedDataset` is a lightweight container for examples and metadata.

In [2]:
examples = [
    {"sequence": "ATGCGTAA", "target": 0.91, "source": "demo_a"},
    {"sequence": "atnccgta", "target": 0.54, "source": "demo_b"},
    {"sequence": "GGGGTTTT", "target": 0.22, "source": "demo_c"},
]

dataset = MaterializedDataset(examples, metadata={"task": "promoter_regression"})
frame = dataset.to_pandas()
frame

   sequence  target  source
0  ATGCGTAA    0.91  demo_a
1  atnccgta    0.54  demo_b
2  GGGGTTTT    0.22  demo_c

## Basic sequence transforms

In [3]:
frame["normalized"] = frame["sequence"].map(normalize_sequence)
frame["gc_content"] = frame["normalized"].map(gc_content)
frame

   sequence  target  source normalized  gc_content
0  ATGCGTAA    0.91  demo_a   ATGCGTAA    0.375000
1  atnccgta    0.54  demo_b   ATNCCGTA    0.428571
2  GGGGTTTT    0.22  demo_c   GGGGTTTT    0.500000

## Optional: define a recipe object

`DatasetRecipe` describes how data should be materialized from query results.

In [4]:
recipe = DatasetRecipe(
    name="demo_recipe",
    query="SELECT ?sequence ?target WHERE { ... }",
    label_field="target",
    metadata_fields=("source",),
)

recipe

DatasetRecipe(name='demo_recipe', query='SELECT ?sequence ?target WHERE { ... }', sequence_field='sequence', label_field='target', label_extractor=None, metadata_fields=('source',), provenance={})